version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats_image
    container_name: stat-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_server
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stat-postgres
    ports:
      - "6541:5432"
    volumes:
      - db-stats:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=stats_server
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm_image
    container_name: ewm-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_server
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-postgres
    ports:
      - "6542:5432"
    volumes:
      - db-ewm:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=ewm_server
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

volumes:
  db-stats:
  db-ewm: