CREATE TABLE IF NOT EXISTS hits
(
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app    VARCHAR(100)                            NOT NULL,
    uri    VARCHAR(100)                            NOT NULL,
    ip     VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (hit_id)
);